paurkedal/ocaml-caqti

- .circleci/config.yml
- README.md
If you merge this and then add this project in CircleCI, you'll get CI builds with basically no effort. We could make it faster by making a custom base image, but for a build that takes 3.5 minutes, it doesn't seem worth the effort.
> Add CircleCI build

- caqti-lwt.opam
- lib-lwt/jbuild
According to the release notes for Lwt 4.0, lwt.preemptive is an alias
for lwt.unix since 3.2.0, and they removed the alias in 4.0.
Also, Lwt_log was moved to a separate opam package.
https://github.com/ocsigen/lwt/releases/tag/4.0.0
> Support Lwt 4.0

- lib-driver/caqti_driver_postgresql.ml
Fixed `is_neg` statement in `string_of_ptime_span` function
> fixed ptime span to string conversion in pgsql driver

- lib/caqti_connection_sig.mli
While working with `caqti` I got confused by the documentation as it seemed to use the same suffixes as `Lwt` but a different terminology. In particular the use of "concurrently" made it unclear whether `iter_s`
was an actual `iter_s` or `iter_p` and thus whether it would apply to the rows in order or not.
I made some changes to the documentation of `fold`, `fold_s` and `iter_s` after looking at the source to understand what their actual behaviour was.
The wording might not be perfect but I'd love to hear your thoughts on this and whether you think it's indeed an improvement or not!
> Clarify documentation of CONNECTION's iterators

- CHANGES.md
- lib-driver/caqti_driver_postgresql.ml
- lib/caqti_connect.ml
This is a small PR to fix an issue that has been causing us a bit of trouble when trying to use `caqti`.
In the postgres documentation [here](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) it states that valid postgres URIs can use either the `postgresql` or `postgres` scheme. It seems like the `postgres` scheme is quite common, for example when deploying to heroku.
The fix here is to handle the special case when resolving the driver name at connect time, and for the `caqti-driver-postgresql` library to register itself for both schemes.
I would be interested in your thoughts/feedback on this, including whether registering the driver twice is indeed the right approach - it is definitely the simplest, but there might be a nicer way.
> Use the postgresql driver when postgres is specified as the URI schema

- lib-driver/caqti_driver_mariadb.ml
- lib-driver/caqti_driver_postgresql.ml
- lib-driver/caqti_driver_sqlite3.ml
- lib/caqti_connect.ml
- lib/caqti_connection_sig.mli
- lib/caqti_stream.ml
- lib/caqti_stream.mli
- tests/test_sql.ml
This is a second attempt at implementing the copy mode function discussed in #26, but using the new `populate` method discussed in #27. I have created a new MR since this is quite different from the first attempt, and I am happy to either close that MR or just overwrite the branch as preffered.
Implementing in this way is definitely easier, but there are a couple of things I am unhappy with, specifically:
* Due to the way `Caqti_stream.iter_s` is implemented, the error type for the output must match the error type of the input. This doesn't make a lot of sense in the inbound direction, as there are not likely to be any errors in the input stream. Is it worth creating a new `iter` method that allows the input and output error types to be the same?
* I had a lot of trouble getting the …
> WIP: Add copy mode (take 2)

- lib-driver/caqti_driver_postgresql.ml
- tests/dune
- tests/test_sql.ml
- tests/testkit.ml
This PR updates the postgresql driver to use copy mode when the `populate` function is called, which should resolve #26.
The code is still slightly rough, but I can't see any obvious ways to make it clearer at this point - so any suggestions for that would be very welcome.
> Postgres populate with copy mode

- lib-driver/caqti_driver_sqlite3.ml
- lib/caqti_response_sig.mli
This PR tries to implement the affected_count method for the sqlite backend.
> implement affected_count for sqlite backend

- lib-driver/caqti_driver_sqlite3.ml
- lib/caqti_connection.ml
- lib/caqti_connection_sig.mli
- lib/caqti_response_sig.mli
- tests/test_sql.ml
This PR adds a convenience method for update and delete statements where one wants to check whether any changes happened to the db.
> add method exec_count to Caqti_connection_sig.S

- caqti.opam
- lib/caqti_common_priv.ml
- lib/caqti_common_priv.mli
- lib/caqti_query.ml
- lib/dune
Fixes #49
This is the code that the ppx generates:
```ocaml
let rec equal : t -> t -> Ppx_deriving_runtime.bool =
let __0 () = equal in
((let open! ((Ppx_deriving_runtime)[@ocaml.warning "-A"]) in
fun lhs ->
fun rhs ->
match (lhs, rhs) with
| (L lhs0, L rhs0) ->
((fun (a : string) -> fun b -> a = b)) lhs0 rhs0
| (Q lhs0, Q rhs0) ->
((fun (a : string) -> fun b -> a = b)) lhs0 rhs0
| (P lhs0, P rhs0) -> ((fun (a : int) -> fun b -> a = b)) lhs0 rhs0
| (S lhs0, S rhs0) ->
(let rec loop x y =
match (x, y) with
| ([], []) -> true
| (a::x, b::y) -> ((fun x -> (__0 ()) x) a b) && (loop x y)
| _ -> false in
(fun x -> fun y -> loop x y)) lhs0 rhs0
| _ -> false)
[@ocaml.warning "-A"])[@@ocaml.warning "-39"]
```
> Drop ppx deriving

- tests/bikereg.ml
This fixes the small misspeling of [Ford Prefect](https://en.wikipedia.org/wiki/Ford_Prefect_(character))'s name. :-)
> Ford Prefect misspelling

- lib-driver/caqti_driver_mariadb.mli
- lib-driver/caqti_driver_postgresql.mli
- lib-driver/caqti_driver_sqlite3.mli
- lib/caqti_common_priv.mli
- lib/caqti_connection_sig.mli
- lib/caqti_driver_info.mli
- lib/caqti_error.mli
- lib/caqti_request.mli
- lib/caqti_type_sig.mli
Just a drive-by fix of some typos and dead links that I stumbled across.  No guarantee of exhaustiveness :)
> Fix various documentation typos and formatting

- lib/caqti_connect.ml
- lib/caqti_connect_sig.mli
- tests/bikereg.ml
I'd like to have this for some subcommands of my app that just need one connection briefly to do their work.
Using only `connect` requires adding cleanup in two branches, exception and normal completion (or does it? the tests don't clean up &mdash; still, I think it's better and more future-proof to call `disconnect`). Using a pool would require adding code at the end to drain the pool, to get the same effect. So neither `connect` alone nor a pool give a nice way to run just a few operations quickly.
The signature of the callback is the same as in `Pool.use`, but with the errors from `CONNECTION.connect`.
I "added" `with_connection` to the tests by modifying `tests/bikereg.ml` to use it.
> Add Caqti_connect_sig.S.with_connection

- lib-driver/caqti_driver_mariadb.ml
- lib-driver/caqti_driver_postgresql.ml
- lib-driver/caqti_driver_sqlite3.ml
- lib/caqti_type.ml
- lib/caqti_type.mli
- lib/caqti_type_sig.mli
- tests/test_sql.ml
This is a possible solution to #64. The enum is merely declared "unknown" to PostgreSQL, which I presume corresponds the old behaviour when no types where passed. (It might also be possible to query the `pg_type` table to acquire the correct OID of enum types, just in time before sending the actual query.)
> Add enum field type.

- lib-driver/caqti_driver_postgresql.ml
Any optional object which first field is NULL was considered missing.
> Fix postgresql backend option detection.

- caqti/lib/caqti_request.ml
In the discussion for PR #77 @paurkedal brought up that caqti offers a
choice between `?` and `$n`. In practice, it was possible to use `?n`
with the sqlite3 driver as long as the number of substitutions
corresponds to the number of arguments. The following query would work:
SELECT * FROM house WHERE color = ?2 AND city = ?1
while the following would fail:
SELECT * FROM house WHERE color = ?2 AND (?1 IS NULL OR city = ?1)
> Disallow ?i non-linear substitutions

- CHANGES.md
Sqlite3 foreign key constraint checks starts from tweaks version 1.8 and not 1.7 as far as I can read from the code.
> CHANGES.md: sqlite3 foreign constraints tweak ver.

- README.md
- caqti/lib/caqti_request.mli
I'm not sure if this change to the README is less clear, but it avoids the now deprecated function `Caqti_request.find`. It also removes a spurious 'e' in Caqti_request.mli.
> Update README from deprecated function, fix typo

- caqti-driver-sqlite3/lib/caqti_driver_sqlite3.ml
In the same file there's another function called [prepare]. While the scopes do not overlap it can be a little confusing when using simple search in the file. I was reading the file and searching for the definition of prepare with simple search and I was surprised to see `PRAGMA foreign_keys = ON` was done each time.
> sqlite3-driver: rename prepare to prepare_db

- caqti/lib/dune
Silences the alert proposed in ocaml/ocaml#11198, but this PR can be merged regardless.
> Add missing dependency on Unix

- CHANGES.md
- caqti.opam
- caqti/lib/caqti_query.ml
- caqti/lib/caqti_query.mli
- caqti/test/test_query.ml
Hi, and thanks for building and maintaining this project :)
As I was playing around I realized that there is some tension when building dynamic queries between the recommended way of using `Caqti_query.t` directly and the "convenient" way of building a query string with `Format`. I ended up writing a `qprintf` function that is like `asprintf`, but generates `Caqti_query.t` instead of strings. A more detailed rationale is in the commit message and replicated below; I find it fairly useful and thought others might too.
Sometimes, you need to construct queries dynamically rather than writing them out in code. Building an ORM would be an obvious reason for doing that, but it is quite often that one has to sprinkle a little bit of dynamism here and there.
In the case that one has to generate …
> Add a printf-like `Caqti_query.qprintf` for dynamic queries

- caqti-mirage.opam
- caqti-mirage/lib/caqti_mirage.ml
- caqti-mirage/lib/caqti_mirage.mli
- caqti-mirage/lib/dune
- caqti-tls.opam
- caqti-tls/testlib/testlib_tls.enabled.ml
the two changes are:
- `Tls.Config.client` now returns a result (here, `Result.get_ok` is used to extract the Ok path -- should there be error handling?)
- mirage-random is deprecated, and now replaced by Mirage_crypto_rng_mirage.S directly.
> update to tls 1.0.0 API

- caqti-driver-postgresql/lib/caqti_driver_postgresql.ml
Broken connections may throw on `db#consume_input`. 
Currently, this means that the first attempt to use a dead Postgres connection from the pool (always) fails, rather than reallocating a fresh connection
> Fix validation of dead connection in postgresql driver
